version: "3.8"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: aabbccdd
      MYSQL_DATABASE: notes
  app:
    image: note-taker
    env_file:
      - .env # Load environment variables from .env file into the service
    ports:
      - "8010:8010"
